export const ADD_TO_WILL_WATCH = "ADD_TO_WILL_WATCH";
export const REMOVE_FROM_WILL_WATCH = "REMOVE_FROM_WILL_WATCH";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";
export const GET_FILMS = "GET_FILMS";
export const SORT_FILMS = "SORT_FILMS";
