import { Grid } from "@mui/material";
import { makeStyles } from "@mui/styles";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { API_URL, API_KEY_3 } from "../src/utils/api";

const useStyles = makeStyles(() => ({
  root: {},

  footer: {},
  image: {
    backgroundColor: "grey",
  },
}));

type Films = {
  adult: boolean;
  backdrop_path: string;
  genre_ids: number[];
  id: number;
  original_language: string;
  original_title: string;
  overview: string;
  popularity: number;
  poster_path: string;
  release_date: Date;
  title: string;
  video: boolean;
  vote_average: number;
  vote_count: number;
};

interface FilmDataProps {
  data: Films[];
}

export default function Home({ data }: FilmDataProps) {
  const classes = useStyles();
  const [filmData, setFilmData] = useState<Films[]>([]);
  //const [sort] = useState("popularity.desc");

  // const getData = useCallback(async () => {
  //   await fetch(`${API_URL}?api_key=${API_KEY_3}&sort_by=${sort}&page=1`)
  //     .then((response) => response.json())
  //     .then((result) => setFilmData(result.results));
  // }, [filmData, sort]);

  useEffect(() => {
    if (data) {
      setFilmData(data);
    }
  }, [data]);

  console.log(data);
  if (!data) {
    return <p>...loading...</p>;
  }

  return (
    <>
      <Head>
        <title>Film Collection App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid container className={classes.root}>
        <Grid container item xs={2}>
          <Grid>buttons</Grid>
        </Grid>
        <Grid container item xs={10}>
          {filmData?.map((it) => {
            return (
              <Grid item xs={6} key={it?.id} p={2}>
                <Image
                  className={classes.image}
                  src={`https://image.tmdb.org/t/p/w500${
                    it.backdrop_path || it.poster_path
                  }`}
                  alt="Vercel Logo"
                  width={160}
                  height={90}
                  layout="responsive"
                  objectFit="contain"
                />
              </Grid>
            );
          })}
        </Grid>
      </Grid>

      <footer className={classes.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by{"Alena Piachenka"}
          <span className={classes.footer}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch(`${API_URL}?api_key=${API_KEY_3}&page=1`);
  const data = await res.json();

  return {
    props: { data: data?.results }, // will be passed to the page component as props
  };
}
